name = input("Enter name: ")             
age = int(input("Enter age: "))         
phone = input("Enter phone: ")         
email = input("Enter email: ")          
gender = input("Enter gender: ")         
city = input("Enter city: ")     

print(f"\n--- Personal Record ---")
print(f"Name ({type(name).__name__}): {name}")
print(f"Age ({type(age).__name__}): {age}")
print(f"Phone ({type(phone).__name__}): {phone}")
print(f"Email ({type(email).__name__}): {email}")
print(f"Gender ({type(gender).__name__}): {gender}")
print(f"City ({type(city).__name__}): {city}")
